version: "3.9"

services:
  web:
    image: nginx:alpine
    container_name: pk-example-web
    restart: unless-stopped
    ports:
      # Host port assigned by PortKeeper (fallback 8080)
      - "${HOST_HTTP_PORT:-8080}:80"
    env_file:
      - .env
    environment:
      # Just for demonstration; NGINX listens on 80 internally
      - NGINX_PORT=80
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:80 || exit 1"]
      interval: 10s
      timeout: 2s
      retries: 5

networks:
  default:
    name: pk-example-net
